title: Drone Meteorite Searching Documentation
remote_theme: just-the-docs/just-the-docs

nav_enabled: false

plugins:
  - jekyll-remote-theme

url: desertfireballnetwork.github.io/drone_meteorite_doc/

exclude:
  - README.md
  - "**/README.md"

logo: "/assets/images/logo.png"