title: Drone Meteorite Searching Documentation
remote_theme: just-the-docs/just-the-docs

nav_enabled: false

plugins:
  - jekyll-remote-theme

url: "https://desertfireballnetwork.github.io"
baseurl: "/drone_meteorite_doc"

exclude:
  - README.md
  - "**/README.md"

logo: "assets/images/logo.png"

color_scheme: dark


gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/desertfireballnetwork/drone_meteorite_doc"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
